# This GitHub Actions workflow is designed to execute Cypress tests with the option
# to select the browser dynamically at run-time.
# It supports manual triggers and handles inputs for browser selection.

name: 02_Select Browser at run-time

on:
  # Manual Trigger with browser selection input
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser (CHROME | EDGE | ELECTRON | FIREFOX)"
        options:
          - "CHROME"
          - "EDGE"
          - "ELECTRON"
          - "FIREFOX"
        required: true
        default: "CHROME"
        type: choice
jobs:
  ui_tests_browser_selected:
    # Machine on which tests will execute
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checking out the code from the GitHub repository to the machine (ubuntu-latest)
      - name: Checkout code
        uses: actions/checkout@v4
      # Step 2: Installing Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # Step 3: Ensure package-lock.json exists before running npm ci
      - name: Check for package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, running npm install to generate it..."
            npm install
          fi
     # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Ensure Cypress is installed
      - name: Install Cypress
        run: npx cypress install

      # Step 6: Run Cypress tests on Chrome browser
      - name: Run Cypress UI tests
        run: npm run cy:tests:${{ github.event.inputs.browser }}

      # Step 7: Upload test reports as artifacts (ensure the path exists)
      - name: Upload Reports
        if: success() || failure()  # Ensure reports are uploaded even on failure
        uses: actions/upload-artifact@v4
        with:
          name: UI Tests Report
          path: cypress/reports

