name: 03_All Supported Browsers

on:
  # Manual Trigger with all supported browsers
  workflow_dispatch:

jobs:
  ui_tests_ALL_browsers:
    runs-on: ubuntu-latest

    # Step 1: Use matrix strategy for parallel test execution on different browsers
    strategy:
      matrix:
        browser: [CHROME, FIREFOX, ELECTRON, EDGE]

    steps:
      # Step 2: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use the latest LTS version

      # Step 4: Ensure package-lock.json exists before running npm ci
      - name: Check for package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found, running npm install to generate it..."
            npm install
          fi

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 6: Ensure Cypress is installed
      - name: Install Cypress
        run: npx cypress install

      # Step 7: Run Cypress tests for the specific browser from the matrix
      - name: Run Cypress UI tests on ${{ matrix.browser }}
        run: npm run cy:tests:${{ matrix.browser }}

      # Step 8: Upload test reports as artifacts (unique name for each browser)
      - name: Upload Reports
        if: success() || failure()  # Ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: UI-Tests-Report-${{ matrix.browser }}  # Unique artifact name per browser
          path: cypress/reports
